### ISSUE TITLE
indexed plone6/volto objects have no @id property, cannot be displayed as search results

### ISSUE THREAD

**Issue by animus888** [rohberg/volto-searchkit-block#12]
Hello there,

I would like to use this add-on with volto/plone6 objects.
Maybe there was something wrong with my mappings.json file, but my indexed volto objects (with collective.elastic.ingest and collective.elastic.plone) have no @id property.
That's why I receive a "cannot receive properties of undefined"-error in the flattenESUrlToPath function --> src/components/helpers.jsx#L18

I used following workaround for this  problem to display the search results in the TestSearchkitQuerystrings view:

src/components/Views/TestSearchkitQuerystrings.jsx#L86
`<Link to={flattenESUrlToPath(result['@components']['navigation']['@id'])} target="_blank">`

src/components/helpers.jsx#L21
`for (let i = 4; i < (pathArray.length-1); i++) {`

here I posted my mappings.json in an collective.elastic.ingest issue:
https://github.com/collective/collective.elastic.ingest/issues/17

As I said, I'm not really sure if this issue could be already resolved by changing the mappings.json file.

**Comment by ksuess** [comment]
Hello @animus888. Be sure to index '@id' in ElasticSearch. Therefore check your mapping.json, that it does not explicitly remove the '@id' from mapping / indexing.

**Comment by ksuess** [comment]
> Hello @animus888. Be sure to index '@id' in ElasticSearch. Therefore check your preprocessings.json, that it does not explicitly remove the '@id' from indexing.

EDIT: mappings.json -> preprocessings.json

**Comment by animus888** [comment]
thanks, you were right. the problem was that  '@id' got removed by the default preprocessings.json I was using.

**Comment by animus888** [comment]
Solved by editing preprocessings.json
